console.log(false === false);       //true
console.log(4 === 4);               //true
console.log(false === false);       //true
console.log([] === false);          //false
console.log("" === false);          //false
console.log(null === false);        //false
console.log(0 === "0");             //false
console.log(null === undefined);    //false
console.log([1,2] === "1,2");       //false
console.log(NaN === NaN);           //false
console.log([] === ![]);            //false